<a href="https://colab.research.google.com/github/Nimika19/Mathematics/blob/main/Practice_for_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve

# Define the matrix C
C = np.array([[3, 1, -1], [2, 4, 1], [1, -1, 2]])

# Perform LU decomposition
lu, piv = lu_factor(C)

# Check if row exchanges were needed
if np.any(piv != np.arange(len(piv))):
    print("Row exchanges are needed.")
else:
    print("Row exchanges are not needed.")

Row exchanges are not needed.


In [5]:
import numpy as np

# Define the matrix B
B = np.array([[2, 3], [-2, -1]])

# Calculate the characteristic polynomial
p = np.poly(B)

# Print the characteristic polynomial
print("Characteristic polynomial:", p)

# Calculate the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(B)

# Print the eigenvalues and eigenvectors
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Characteristic polynomial: [ 1. -1.  4.]
Eigenvalues: [0.5+1.93649167j 0.5-1.93649167j]
Eigenvectors: [[ 0.77459667+0.j   0.77459667-0.j ]
 [-0.38729833+0.5j -0.38729833-0.5j]]


In [6]:
import numpy as np

# Define the matrix B
B = np.array([[2, 0, 1], [1, 1, 0], [0, 1, 1], [1, 2, 0]])

# Perform QR decomposition
Q, R = np.linalg.qr(B)

print("Matrix B:")
print(B)
print("\nQR Decomposition:")
print("Q:")
print(Q)
print("\nR:")
print(R)

Matrix B:
[[2 0 1]
 [1 1 0]
 [0 1 1]
 [1 2 0]]

QR Decomposition:
Q:
[[-0.81649658  0.47140452 -0.28867513]
 [-0.40824829 -0.23570226  0.28867513]
 [-0.         -0.47140452 -0.8660254 ]
 [-0.40824829 -0.70710678  0.28867513]]

R:
[[-2.44948974e+00 -1.22474487e+00 -8.16496581e-01]
 [ 0.00000000e+00 -2.12132034e+00 -5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00 -1.15470054e+00]]


In [12]:
import numpy as np

# Define the vectors
v1 = np.array([1, 1, 0])
v2 = np.array([1, 0, 1])
v3 = np.array([0, 1, 1])

# Initialize the orthogonalized vectors
u1 = v1
u2 = v2
u3 = v3

# Perform Gram-Schmidt orthogonalization
u2 = u2 - np.dot(u2, u1) / np.dot(u1, u1) * u1
u3 = u3 - np.dot(u3, u1) / np.dot(u1, u1) * u1 - np.dot(u3, u2) / np.dot(u2, u2) * u2

print("Orthogonalized vectors:")
print(u1)
print(u2)
print(u3)

Orthogonalized vectors:
[1 1 0]
[ 0.5 -0.5  1. ]
[-0.66666667  0.66666667  0.66666667]


In [15]:
def lagrange_interpolation(x_values, y_values, x):
    result = 0
    for i in range(len(x_values)):
        numerator = 1
        denominator = 1
        for j in range(len(x_values)):
            if i != j:
                numerator *= (x - x_values[j])
                denominator *= (x_values[i] - x_values[j])
        result += f_x_values[i] * numerator / denominator
    return result

x_values = [1, 4, 7, 10]
f_x_values = [2, 5, 10, 12]
x = 6

result = lagrange_interpolation(x_values, f_x_values, x)
print("Interpolated value at X =", x, "is", result)

Interpolated value at X = 6 is 8.419753086419753
